export const sliderData = [
  {
    imageURL:
      "https://res.cloudinary.com/dx6zgsncl/image/upload/v1638607253/Lucky/Carousel/Carousel%20-%20compressed/one_beach_lzgzpm_evkqhj.jpg",
    gradientColor: "459CA2",
    textColor: "fff",
    directon: "90deg",
    Headline__1: "DON'T JUST UNDERGO",
    Headline__2: "TRAVEL. HAVE A TRAVEL",
    Headline__3: "EXPERIENCE.",
    sub1: "Our dedicated team of travel experts are on hand to",
    sub2: "design itineraries just for you to ensure you have",
    sub3: "travel experiences to remember.",
    buttonColor: "",
  },
  {
    imageURL:
      "https://res.cloudinary.com/dx6zgsncl/image/upload/v1638607253/Lucky/Carousel/Carousel%20-%20compressed/two_ice_krcaja_n89a3y.jpg",
    gradientColor: "E1E0DF",
    textColor: "28538C",
    Headline__1: "ACCESS A GLOBAL",
    Headline__2: "NETWORK OF HOTELS",
    Headline__3: "AND RESORTS.",
    sub1: "We have onboarded a global panel of hotels and",
    sub2: "resorts to give you the best prices for the best",
    sub3: "locations all year round.",
    buttonColor: "#28538C",
  },
  {
    imageURL:
      "https://res.cloudinary.com/dx6zgsncl/image/upload/v1638607253/Lucky/Carousel/Carousel%20-%20compressed/three_building_hhhzq3_ovwgpu.jpg",
    gradientColor: "2B3BB3",
    textColor: "fff",
    Headline__1: "A PERSONAL TRAVEL",
    Headline__2: "ASSISTANT FOR YOUR",
    Headline__3: "ORGANISATION.",
    sub1: "A world class travel agency combined with a state-",
    sub2: "of-the-art travel platform to keep your employees",
    sub3: "organised and your travel costs low.",
    buttonColor: "",
  },
  {
    imageURL:
      "https://res.cloudinary.com/dx6zgsncl/image/upload/v1638607253/Lucky/Carousel/Carousel%20-%20compressed/four_ocean_sozoyk_jjbkgo.jpg",
    gradientColor: "52BEFA",
    textColor: "fff",
    Headline__1: "GET MORE OUT OF YOUR",
    Headline__2: "TRAVEL BY MAKING IT A",
    Headline__3: "PACKAGE.",
    sub1: "Our trusted panel of intermediaries provide you with",
    sub2: "ready made packages to maximise your trip by",
    sub3: "simplifying your schedule.",
    buttonColor: "",
  },
  {
    imageURL:
      "https://res.cloudinary.com/dx6zgsncl/image/upload/v1638607253/Lucky/Carousel/Carousel%20-%20compressed/five_jungle_tky2z0_rktxlt.jpg",
    gradientColor: "E65F2D",
    textColor: "28538C",
    Headline__1: "REMOVE THE BURDEN OF",
    Headline__2: "PAPERWORK AND",
    Headline__3: "FINANCIAL RISK.",
    sub1: "We can handle all your documentation, from visas to entry",
    sub2: "forms, and our panel of insurers will cover your financial",
    sub3: "risk in uncertain times.",
    buttonColor: "#28538C",
  },
  {
    imageURL:
      "https://res.cloudinary.com/dx6zgsncl/image/upload/v1638607253/Lucky/Carousel/Carousel%20-%20compressed/six_rome_xxoee9_ijlszv.jpg",
    gradientColor: "184D87",
    textColor: "fff",
    Headline__1: "KNOW THE RULES FOR",
    Headline__2: "ANY DESTINATION FOR",
    Headline__3: "ANY FACT PATTERN",
    sub1: "We regularly stay in touch with travel providers",
    sub2: "and authorities to make sure we know the rules, so",
    sub3: "you don't have to.",
    buttonColor: "",
  },
];
